[B001-C0005] Connect git-deck and git hooks message - The first part.
Deck-Link: https://github.com/hoss-java/githooks/blob/main/DECK.md#001-0005
Change-Id: I07a7345592aa34ac144b786a03792a19d7198c4e

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -36,17 +36,26 @@ fi
 
 #---------------------------------------
 # Import msg formatter
-msgline=$(head -1 $1)
-DECK_PATH=.git/hooks/deckpath.shinc
-MSGFORMATTER_PATH=.git/hooks/commit-msg-format.shinc
-if [ -f "$MSGFORMATTER_PATH" ]; then
-. ${MSGFORMATTER_PATH}
+GIT_ROOT="$(git rev-parse --show-toplevel)"
+GITHOOK_DEFAULT_FILE="$GIT_ROOT/.gitdefault"
+if [ -f "$GITHOOK_DEFAULT_FILE" ]; then
+    . "$GITHOOK_DEFAULT_FILE"
+else
+    deckLinkFlag=false
+    gerritChangeIdFlag=true
+fi
+
+COMMIT_MSG_FORMAT_SHINC=.git/hooks/commit-msg-format.shinc
+if [ -f "$COMMIT_MSG_FORMAT_SHINC" ]; then
+    . ${COMMIT_MSG_FORMAT_SHINC}
 fi
 #---------------------------------------
 
-# Do not create a change id if requested
-if test "false" = "`git config --bool --get gerrit.createChangeId`" ; then
-  exit 0
+if [ "$gerritChangeIdFlag" = true ]; then
+    # Do not create a change id if requested
+    if test "false" = "`git config --bool --get gerrit.createChangeId`" ; then
+        exit 0
+    fi
 fi
 
 # $RANDOM will be undefined if not using bash, so don't use set -u
@@ -56,33 +65,34 @@ dest="$1.tmp.${random}"
 trap 'rm -f "${dest}"' EXIT
 
 if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
-   echo "cannot strip comments from $1"
-   exit 1
+    echo "cannot strip comments from $1"
+    exit 1
 fi
 
 if test ! -s "${dest}" ; then
-  echo "file is empty: $1"
-  exit 1
+    echo "file is empty: $1"
+    exit 1
 fi
 
 #---------------------------------------
 # Import Deck link adder
-DECKLINKADDER_PATH=.git/hooks/commit-msg-decklink.shinc
-if [ -f "$DECKLINKADDER_PATH" ]; then
-. ${DECK_PATH}
-. ${DECKLINKADDER_PATH}
+COMMIT_MSG_DECKLINK_SHINC=.git/hooks/commit-msg-decklink.shinc
+if [ -f "$COMMIT_MSG_DECKLINK_SHINC" ]; then
+    . ${COMMIT_MSG_DECKLINK_SHINC}
 fi
 #---------------------------------------
 
-# Avoid the --in-place option which only appeared in Git 2.8
-# Avoid the --if-exists option which only appeared in Git 2.15
-if ! git -c trailer.ifexists=doNothing interpret-trailers \
-      --trailer "Change-Id: I${random}" < "$1" > "${dest}" ; then
-  echo "cannot insert change-id line in $1"
-  exit 1
-fi
+if [ "$gerritChangeIdFlag" = true ]; then
+    # Avoid the --in-place option which only appeared in Git 2.8
+    # Avoid the --if-exists option which only appeared in Git 2.15
+    if ! git -c trailer.ifexists=doNothing interpret-trailers \
+          --trailer "Change-Id: I${random}" < "$1" > "${dest}" ; then
+        echo "cannot insert change-id line in $1"
+        exit 1
+    fi
 
-if ! mv "${dest}" "$1" ; then
-  echo "cannot mv ${dest} to $1"
-  exit 1
+    if ! mv "${dest}" "$1" ; then
+        echo "cannot mv ${dest} to $1"
+        exit 1
+    fi
 fi
