[B001-C0001] test manual action to update gh project boards - patch 2.
Deck-Link: https://github.com/hoss-java/githooks/blob/main/DECK.md#001-0001
Change-Id: I333fcf5f3e4221001ea06622935e6d4b62ca9a89

diff --git a/.github/workflows/update-gh-projects.yml b/.github/workflows/update-gh-projects.yml
--- a/.github/workflows/update-gh-projects.yml
+++ b/.github/workflows/update-gh-projects.yml
@@ -26,6 +26,13 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.TAP }}  # Reference your secret token here
         run: |
+          echo "Using repository: $GITHUB_REPO"  # Check if this prints right
+          echo "Using GITHUB_TOKEN: ${GITHUB_TOKEN}"  # Avoid printing sensitive methods
+          # Check if the token is set
+          if [ -z "$GITHUB_TOKEN" ]; then
+            echo "Error: GITHUB_TOKEN is not set. Exiting."
+            exit 1
+          fi
           chmod +x .github/scripts/git-deck-tools.sh
           ./.github/scripts/git-deck-tools.sh update-gh-projects
 
